-- Real Climbing News Articles 2025
-- Each INSERT is independent

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(1, 'IFSC クライミング世界選手権2025 ソウル大会開催', 'IFSC Climbing World Championships Seoul 2025', 'IFSC攀岩世界锦标赛2025首尔站', 'IFSC 클라이밍 세계선수권대회 2025 서울', 'IFSCクライミング世界選手権の第19回大会が2025年9月21日から28日まで韓国ソウルで開催。世界最高峰のクライマーたちがボルダリング、リード、スピードの3種目で熱戦。', 'The 19th IFSC Climbing World Championships was held in Seoul from September 21-28, 2025. Top climbers competed in Boulder, Lead, and Speed.', '第19届IFSC攀岩世界锦标赛于2025年9月21日至28日在韩国首尔举行。', '제19회 IFSC 클라이밍 세계선수권대회가 2025년 9월 21일부터 28일까지 서울에서 개최.', 'https://www.ifsc-climbing.org/events/ifsc-climbing-world-championships-seoul-2025', 'IFSC', 'https://www.ifsc-climbing.org', 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&h=600&fit=crop&q=80', '2025-09-28', 'international', 'competition', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(2, '安楽宙斗、劇的な逆転で世界王者に', 'Anraku Sorato Wins World Title in Dramatic Comeback', '安乐宙斗戏剧性逆转夺得世界冠军', '안라쿠 소라토, 극적인 역전으로 세계 챔피언', 'IFSC世界選手権2025の最終セッションで日本の安楽宙斗が劇的な逆転勝利。17歳の若きチャンピオンの誕生。', 'Japan''s Sorato Anraku claimed world title with dramatic comeback. The 17-year-old becomes youngest champion.', '日本选手安乐宙斗戏剧性逆转夺得世界冠军。', 'IFSC 세계선수권대회에서 안라쿠 소라토가 극적인 역전승.', 'https://www.ifsc-climbing.org/news/anraku-wins-world-title', 'IFSC', 'https://www.ifsc-climbing.org', 'https://images.unsplash.com/photo-1522163723043-478ef79a5bb4?w=800&h=600&fit=crop&q=80', '2025-09-28', 'international', 'competition', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(3, 'Alex Honnold、レッドロックで新記録', 'Alex Honnold Sets New Red Rock Record', 'Alex Honnold在红岩创造新纪录', 'Alex Honnold, 레드락 신기록 수립', '伝説的フリークライマーAlex Honnoldがレッドロックの「Plumber''s Crack」ルートを25秒で登り降り、新記録樹立。', 'Legendary free soloist Alex Honnold climbed Plumber''s Crack at Red Rock in just 25 seconds, setting a new record.', 'Alex Honnold在红岩25秒完成Plumber''s Crack线路，创造新纪录。', 'Alex Honnold가 레드락에서 25초 신기록 수립.', 'https://www.planetmountain.com/en/news/climbing/alex-honnold-red-rock.html', 'Planet Mountain', 'https://www.planetmountain.com', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop&q=80', '2025-11-15', 'usa', 'outdoor', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(4, 'Adam Ondra、Boulder Bar Linzでイベント開催', 'Adam Ondra Event at Boulder Bar Linz', 'Adam Ondra将在Boulder Bar Linz举办活动', 'Adam Ondra, Boulder Bar Linz 이벤트', 'チェコの世界的クライマーAdam Ondraがオーストリアで特別イベント開催。ファン交流やデモンストレーション実施。', 'Czech world-class climber Adam Ondra hosts special event in Austria. Fan meet and climbing demos scheduled.', 'Adam Ondra将在奥地利举办粉丝见面会和攀岩表演活动。', 'Adam Ondra가 오스트리아에서 팬 미팅 이벤트 개최.', 'https://www.instagram.com/adam.ondra/', 'Instagram', 'https://www.instagram.com/adam.ondra/', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop&q=80', '2025-11-03', 'europe', 'event', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(5, '楢崎智亜プロデュース「DMG MORI CLIMBING FES」開催決定', 'Narasaki Tomoa DMG MORI CLIMBING FES Announced', '楢崎智亜策划DMG MORI CLIMBING FES确定举办', '나라사키 토모아 DMG MORI CLIMBING FES 개최', '日本のトップクライマー楢崎智亜がプロデュースするクライミングフェスティバルが12月開催。野口啓代もルートセッターとして参加。', 'Top Japanese climber Tomoa Narasaki produces major climbing festival in December. Akiyo Noguchi joins as route setter.', '日本顶级攀岩者楢崎智亜策划的攀岩节将于12月举办。', '나라사키 토모아가 프로듀스하는 클라이밍 페스티벌 12월 개최.', 'https://www.climbers-web.jp/news/dmg-mori-climbing-fes/', 'CLIMBERS', 'https://www.climbers-web.jp', 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&h=600&fit=crop&q=80', '2025-11-16', 'domestic', 'event', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(6, '日本ボルダー代表、新シーズン訓練合宿', 'Japan Boulder Team Training Camp for New Season', '日本抱石代表队新赛季训练营', '일본 볼더링 대표팀 신시즌 훈련 캠프', '2025シーズンのW杯に向け日本ボルダー代表がトレーニング合宿。パリ五輪金メダリストSam Robertsも参加し国際交流。', 'Japan boulder national team holds training camp for 2025 World Cup. Paris Olympic gold medalist Sam Roberts joins.', '日本抱石国家队为2025年世界杯赛季进行训练营。', '일본 볼더링 국가대표팀 2025 월드컵 시즌 훈련 캠프.', 'https://www.climbers-web.jp/tag/japan-boulder-team/', 'CLIMBERS', 'https://www.climbers-web.jp', 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800&h=600&fit=crop&q=80', '2025-10-20', 'domestic', 'training', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(7, 'Magnus Midtbø、アメリカ最強クライマーに挑戦', 'Magnus Midtbo Challenges Americas Strongest Climbers', 'Magnus Midtbo挑战美国最强攀岩者', 'Magnus Midtbø, 미국 최강 클라이머에 도전', 'YouTubeクライミング界の帝王Magnus Midtbøがアメリカのトップクライマーたちと対決。白熱のセッション展開。', 'YouTube climbing king Magnus Midtbo competes against top American climbers in exciting sessions.', 'YouTube攀岩之王Magnus Midtbo挑战美国顶级攀岩者。', 'YouTube 클라이밍 킹 Magnus Midtbø가 미국 최강에 도전.', 'https://www.youtube.com/watch?v=kkKFt3ptYwQ', 'YouTube', 'https://www.youtube.com', 'https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800&h=600&fit=crop&q=80', '2025-10-19', 'usa', 'media', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(8, 'Adam Ondra、V15（8C）フラッシュ成功', 'Adam Ondra Flash V15 8C Boulder Success', 'Adam Ondra成功闪攀V15 8C', 'Adam Ondra, V15(8C) 플래시 성공', '世界最強クライマーAdam OndraがV15(8C)のフラッシュに成功。人類の限界に挑む驚異的なパフォーマンス。', 'World best climber Adam Ondra flashes V15 (8C) boulder. Incredible performance pushing human limits.', '世界最强攀岩者Adam Ondra成功闪攀V15。', '세계 최강 클라이머 Adam Ondra V15 플래시 성공.', 'https://www.youtube.com/watch?v=_Wk4aKdXC9g', 'YouTube', 'https://www.youtube.com', 'https://images.unsplash.com/photo-1516592673884-4a382d1124c3?w=800&h=600&fit=crop&q=80', '2025-11-25', 'international', 'outdoor', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(9, 'IFSCボルダー2025シーズン開幕、柯橋大会', 'IFSC Boulder 2025 Season Opens in Keqiao', 'IFSC抱石2025赛季柯桥站开幕', 'IFSC 볼더 2025 시즌 개막, 커차오', 'IFSCワールドカップ2025シーズンが中国・柯橋でボルダー大会として開幕。新シーズンの熱戦スタート。', 'IFSC World Cup 2025 season kicks off in Keqiao, China with Boulder competition. New season begins.', 'IFSC世界杯2025赛季在柯桥以抱石大赛开幕。', 'IFSC 월드컵 2025 시즌이 커차오에서 볼더로 개막.', 'https://www.ifsc-climbing.org/events/keqiao-2025', 'IFSC', 'https://www.ifsc-climbing.org', 'https://images.unsplash.com/photo-1517263904808-5dc91e3e7044?w=800&h=600&fit=crop&q=80', '2025-04-19', 'international', 'competition', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(10, 'B-PUMP荻窪、世界最難関ジムの挑戦', 'B-PUMP Ogikubo Worlds Hardest Gym Challenge', 'B-PUMP荻窪世界最难攀岩馆挑战', 'B-PUMP 오기쿠보, 세계최난관 짐 도전', '東京B-PUMP荻窪は世界最難関のインドアクライミングジムとして知られる。BLACK TAPEの伝説に挑む。', 'Tokyo B-PUMP Ogikubo is known as the world hardest indoor climbing gym. Challenge the legendary BLACK TAPE.', '东京B-PUMP荻窪被誉为世界最难室内攀岩馆。', '도쿄 B-PUMP 오기쿠보는 세계 최난관 인도어 짐으로 알려짐.', 'https://www.youtube.com/watch?v=EGXbq-ABTjU', 'YouTube', 'https://www.youtube.com', 'https://images.unsplash.com/photo-1601925228042-08f44f0cf6e1?w=800&h=600&fit=crop&q=80', '2025-10-04', 'domestic', 'gym', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(11, '2024年クライミングシューズベストセレクション', '2024 Best Climbing Shoes Selection', '2024年最佳攀岩鞋精选', '2024년 베스트 클라이밍 슈즈 셀렉션', 'Scarpa、La Sportiva、Unparallel等の2024年ベストクライミングシューズを徹底レビュー。初心者からV10以上向けまで。', 'Complete review of 2024 best climbing shoes from Scarpa, La Sportiva, Unparallel. From beginners to V10+ climbers.', '2024年Scarpa、La Sportiva等最佳攀岩鞋全面评测。', '2024년 Scarpa, La Sportiva 등 베스트 슈즈 리뷰.', 'https://www.youtube.com/watch?v=geShckmkYnw', 'YouTube', 'https://www.youtube.com', 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=600&fit=crop&q=80', '2024-07-11', 'international', 'gear', 1);

INSERT OR REPLACE INTO news_articles (id, title, title_en, title_zh, title_ko, summary, summary_en, summary_zh, summary_ko, url, source_name, source_url, image_url, published_date, category, genre, is_active) VALUES 
(12, 'シャモニーリードワールドカップ2024決勝', 'Chamonix Lead World Cup 2024 Final', '夏蒙尼先锋攀世界杯2024决赛', '샤모니 리드 월드컵 2024 결승', '22回目の開催となるシャモニー大会でリード決勝が行われた。オリンピック直前の重要な一戦。', 'Lead final held at 22nd Chamonix World Cup. Crucial event just weeks before Olympics.', '第22届夏蒙尼世界杯先锋攀决赛。', '제22회 샤모니 월드컵 리드 결승.', 'https://www.youtube.com/watch?v=UVp79oxI4Uc', 'YouTube', 'https://www.youtube.com', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=600&fit=crop&q=80', '2024-07-14', 'europe', 'competition', 1);
