-- Mock News Articles for Testing

INSERT INTO news_articles (
  title, title_en, title_zh, title_ko,
  summary, summary_en, summary_zh, summary_ko,
  url, source_name, image_url, published_date,
  category, genre, language
) VALUES
('Adam Ondra sends V17/9A boulder problem in Norway', 
 'Adam Ondra sends V17/9A boulder problem in Norway',
 '亚当·昂德拉完成挪威V17/9A抱石线路',
 '아담 온드라, 노르웨이서 V17/9A 볼더링 완등',
 'Czech climber Adam Ondra has successfully climbed one of the world''s hardest boulder problems, graded V17 (9A), in Flatanger, Norway.',
 'Czech climber Adam Ondra has successfully climbed one of the world''s hardest boulder problems, graded V17 (9A), in Flatanger, Norway.',
 '捷克攀岩者亚当·昂德拉成功完成挪威弗拉坦格尔的世界最难抱石线路V17（9A）。',
 '체코 클라이머 아담 온드라가 노르웨이 플라탕에르에서 세계 최고난이도 볼더링 과제 V17(9A)를 완등했습니다.',
 'https://example.com/ondra-v17-norway',
 'Climbing Magazine',
 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800',
 datetime('now'),
 'bouldering', 'achievement', 'en'),

('IFSC World Cup Finals 2025 Schedule Announced',
 'IFSC World Cup Finals 2025 Schedule Announced',
 'IFSC世界杯总决赛2025赛程公布',
 'IFSC 월드컵 파이널 2025 일정 발표',
 'The International Federation of Sport Climbing has announced the schedule for the 2025 World Cup Finals, featuring lead, bouldering, and speed events.',
 'The International Federation of Sport Climbing has announced the schedule for the 2025 World Cup Finals, featuring lead, bouldering, and speed events.',
 '国际运动攀登联合会公布2025年世界杯总决赛赛程，包括先锋、抱石和速度赛。',
 '국제스포츠클라이밍연맹이 2025년 월드컵 파이널 일정 발표. 리드, 볼더링, 스피드 종목 포함.',
 'https://example.com/ifsc-2025-finals',
 'IFSC Official',
 'https://images.unsplash.com/photo-1564769610726-4d98dd2e28ce?w=800',
 datetime('now', '-1 day'),
 'competition', 'event', 'en'),

('New Climbing Gym Opens in Tokyo with 120+ Routes',
 'New Climbing Gym Opens in Tokyo with 120+ Routes',
 '东京新开设拥有120+线路的攀岩馆',
 '도쿄에 120+ 루트 보유한 새 클라이밍 짐 오픈',
 'A state-of-the-art climbing facility has opened in central Tokyo, featuring over 120 routes for all skill levels, plus a café and gear shop.',
 'A state-of-the-art climbing facility has opened in central Tokyo, featuring over 120 routes for all skill levels, plus a café and gear shop.',
 '东京市中心开设最新攀岩设施，拥有120+条适合所有水平的线路，配备咖啡馆和装备商店。',
 '도쿄 중심가에 최신설비 클라이밍 시설 오픈. 모든 레벨 대응 120+ 루트, 카페와 장비샵 병설.',
 'https://example.com/tokyo-gym-opening',
 'Climbing Business Journal',
 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
 datetime('now', '-2 days'),
 'news', 'facility', 'en'),

('Study Shows Climbing Improves Mental Health',
 'Study Shows Climbing Improves Mental Health',
 '研究显示攀岩改善心理健康',
 '연구: 클라이밍이 정신건강 개선',
 'A new study published in the Journal of Sport Psychology demonstrates that regular climbing practice significantly reduces stress and anxiety levels.',
 'A new study published in the Journal of Sport Psychology demonstrates that regular climbing practice significantly reduces stress and anxiety levels.',
 '《运动心理学杂志》发表的新研究表明，定期攀岩练习显著降低压力和焦虑水平。',
 '스포츠심리학 저널에 발표된 새 연구에서 정기적인 클라이밍 연습이 스트레스와 불안 수준을 크게 감소시킨다고 입증.',
 'https://example.com/climbing-mental-health-study',
 'Science Daily',
 'https://images.unsplash.com/photo-1599809275671-b5942cabc7a2?w=800',
 datetime('now', '-3 days'),
 'other', 'research', 'en'),

('Legendary Climber Lynn Hill Celebrates 30 Years Since El Cap Free Ascent',
 'Legendary Climber Lynn Hill Celebrates 30 Years Since El Cap Free Ascent',
 '传奇攀岩者林恩·希尔庆祝酋长岩自由攀登30周年',
 '전설적 클라이머 린 힐, 엘캡 프리 등반 30주년',
 'Lynn Hill reflects on her historic 1993 free ascent of The Nose on El Capitan, a feat that revolutionized big wall climbing.',
 'Lynn Hill reflects on her historic 1993 free ascent of The Nose on El Capitan, a feat that revolutionized big wall climbing.',
 '林恩·希尔回顾她1993年酋长岩"鼻子"路线的自由攀登，这一壮举革新了大岩壁攀登。',
 '린 힐이 1993년 엘캡 "더 노즈" 프리 등반을 회고. 빅월 클라이밍에 혁명을 일으킨 위업 30주년.',
 'https://example.com/lynn-hill-30-years',
 'Rock and Ice',
 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
 datetime('now', '-4 days'),
 'alpine', 'history', 'en');
