-- Migration: Add sample video data for testing
-- Created: 2024-12-23

-- Insert sample YouTube climbing videos
INSERT OR IGNORE INTO videos (
  id, title, title_en, title_zh, title_ko,
  description, description_en, description_zh, description_ko,
  media_source, url, thumbnail_url,
  channel_name, posted_date, duration,
  views, likes, category,
  created_at
) VALUES 
-- Video 1: Alex Honnold Free Solo
(1, 
 'アレックス・オノルド フリーソロ エルキャピタン', 
 'Alex Honnold Free Solo El Capitan',
 '亚历克斯·霍诺尔德自由攀登酋长岩',
 '알렉스 호놀드 프리솔로 엘캐피탄',
 'エルキャピタンをロープなしで登る伝説的な挑戦',
 'Legendary climb of El Capitan without ropes',
 '无绳攀登酋长岩的传奇挑战',
 '로프 없이 엘캐피탄을 등반하는 전설적인 도전',
 'youtube', 
 'https://www.youtube.com/watch?v=urRVZ4SW7WU',
 'https://i.ytimg.com/vi/urRVZ4SW7WU/maxresdefault.jpg',
 'National Geographic', 
 '2018-09-03', 
 '240',
 5234000, 89000, 'sport',
 '2024-01-01 00:00:00'),

-- Video 2: Adam Ondra Project Hard
(2,
 'アダム・オンドラ 史上最難課題への挑戦',
 'Adam Ondra Project Hard Challenge',
 '亚当·翁德拉挑战史上最难项目',
 '아담 온드라 역대 최고난이도 도전',
 '世界最高峰のクライマーによる究極の挑戦',
 'Ultimate challenge by world''s best climber',
 '世界顶级攀岩者的终极挑战',
 '세계 최고 클라이머의 궁극적 도전',
 'youtube',
 'https://www.youtube.com/watch?v=ZRTNHDd0gL8',
 'https://i.ytimg.com/vi/ZRTNHDd0gL8/maxresdefault.jpg',
 'Adam Ondra',
 '2019-11-15',
 '420',
 3456000, 72000, 'sport',
 '2024-01-02 00:00:00'),

-- Video 3: Shauna Coxsey Boulder World Cup
(3,
 'ショーナ・コクシー ボルダリングワールドカップ優勝',
 'Shauna Coxsey Boulder World Cup Victory',
 '肖纳·考克西抱石世界杯夺冠',
 '샤우나 콕시 볼더링 월드컵 우승',
 'ワールドカップでの圧倒的なパフォーマンス',
 'Dominant performance at World Cup',
 '世界杯上的统治性表现',
 '월드컵에서의 압도적인 퍼포먼스',
 'youtube',
 'https://www.youtube.com/watch?v=Kh_HfWoQbDc',
 'https://i.ytimg.com/vi/Kh_HfWoQbDc/maxresdefault.jpg',
 'IFSC Climbing',
 '2019-08-20',
 '180',
 2890000, 54000, 'boulder',
 '2024-01-03 00:00:00'),

-- Video 4: Magnus Midtbø Climbing Challenges
(4,
 'マグナス・ミッドボー クライミングチャレンジ',
 'Magnus Midtbø Climbing Challenges',
 '马格努斯·米特伯攀岩挑战',
 '마그누스 미드보 클라이밍 챌린지',
 '元プロクライマーによる様々なチャレンジ',
 'Various challenges by former pro climber',
 '前职业攀岩者的各种挑战',
 '전 프로 클라이머의 다양한 챌린지',
 'youtube',
 'https://www.youtube.com/watch?v=r-BkWW0SREw',
 'https://i.ytimg.com/vi/r-BkWW0SREw/maxresdefault.jpg',
 'Magnus Midtbø',
 '2020-03-12',
 '600',
 4123000, 98000, 'boulder',
 '2024-01-04 00:00:00'),

-- Video 5: Tomoa Narasaki Tokyo Olympics
(5,
 '楢崎智亜 東京オリンピック クライミング',
 'Tomoa Narasaki Tokyo Olympics Climbing',
 '楢崎智亚东京奥运会攀岩',
 '나라사키 토모아 도쿄 올림픽 클라이밍',
 '東京オリンピックでの日本代表の活躍',
 'Japan''s performance at Tokyo Olympics',
 '东京奥运会上日本代表的表现',
 '도쿄 올림픽에서 일본 대표의 활약',
 'youtube',
 'https://www.youtube.com/watch?v=j8HiSkX_shY',
 'https://i.ytimg.com/vi/j8HiSkX_shY/maxresdefault.jpg',
 'Olympics',
 '2021-08-06',
 '360',
 6789000, 145000, 'sport',
 '2024-01-05 00:00:00'),

-- Video 6: Janja Garnbret World Championship
(6,
 'ヤーニャ・ガルンブレット 世界選手権',
 'Janja Garnbret World Championship',
 '雅尼娅·加恩布雷特世界锦标赛',
 '야냐 가른브렛 세계선수권',
 '女王による完璧なパフォーマンス',
 'Perfect performance by the queen',
 '女王的完美表现',
 '여왕의 완벽한 퍼포먼스',
 'youtube',
 'https://www.youtube.com/watch?v=kk8EGQD2P-0',
 'https://i.ytimg.com/vi/kk8EGQD2P-0/maxresdefault.jpg',
 'IFSC Climbing',
 '2019-09-18',
 '300',
 3567000, 78000, 'sport',
 '2024-01-06 00:00:00');

-- Update video statistics for ranking
UPDATE videos SET views = views + RANDOM() % 100000 WHERE id <= 6;
UPDATE videos SET likes = likes + RANDOM() % 10000 WHERE id <= 6;
