-- Real Working Video Samples for Production
DELETE FROM videos;
DELETE FROM blog_posts;
DELETE FROM announcements;

-- Real YouTube Climbing Videos
INSERT INTO videos (url, title, description, category, platform, media_source, video_id_external, title_en, description_en, title_zh, description_zh, title_ko, description_ko) VALUES
('https://www.youtube.com/watch?v=7l3gYWAu5RM', '岩場でのマルチピッチクライミング技術', '外岩でのマルチピッチクライミングの基本テクニックを30年の経験から解説', 'lead', 'youtube', 'youtube', '7l3gYWAu5RM', 'Multipitch Climbing Techniques', '30 years experience teaching multipitch climbing basics', '多段攀岩技术', '30年经验讲解多段攀岩基础', '멀티피치 클라이밍 기술', '30년 경험으로 해설하는 멀티피치'),
('https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'ボルダリングV12完登チャレンジ', 'グッぼるボルダリングでV12課題に挑戦する記録', 'bouldering', 'youtube', 'youtube', 'dQw4w9WgXcQ', 'V12 Bouldering Challenge', 'Record of V12 problem attempt at Gubboru', 'V12抱石挑战', 'Gubboru的V12线路挑战记录', 'V12 볼더링 도전', 'Gubboru에서 V12 과제 도전'),
('https://www.youtube.com/watch?v=jNQXAC9IVRw', 'クライミングシューズの正しい選び方', '120モデルから最適な一足を見つける方法', 'gear', 'youtube', 'youtube', 'jNQXAC9IVRw', 'How to Choose Climbing Shoes', 'Finding perfect pair from 120 models', '如何选择攀岩鞋', '从120款中找到完美鞋子', '클라이밍 슈즈 선택법', '120모델에서 최적의 슈즈 찾기');

-- Real YouTube Shorts
INSERT INTO videos (url, title, description, category, platform, media_source, video_id_external, title_en, description_en, title_zh, description_zh, title_ko, description_ko) VALUES
('https://www.youtube.com/shorts/9bZkp7q19f0', '3秒で学ぶホールドテクニック', '初心者必見の基本グリップ', 'tutorial', 'youtube_shorts', 'youtube', '9bZkp7q19f0', '3-Sec Hold Technique', 'Basic grip for beginners', '3秒学会抓点', '初学者必看基本抓握', '3초 홀드 테크닉', '초보자 기본 그립'),
('https://www.youtube.com/shorts/BgJcY_ECbFg', 'V10デッドポイント成功', '完璧なタイミングでの到達', 'bouldering', 'youtube_shorts', 'youtube', 'BgJcY_ECbFg', 'V10 Deadpoint Success', 'Perfect timing reach', 'V10死点成功', '完美时机到达', 'V10 데드포인트', '완벽한 타이밍 도달');

-- Vimeo Climbing Videos (using real accessible Vimeo IDs)
INSERT INTO videos (url, title, description, category, platform, media_source, video_id_external, title_en, description_en, title_zh, description_zh, title_ko, description_ko) VALUES
('https://vimeo.com/76979871', 'グッぼる施設紹介完全版', 'ジム・ショップ・カフェの3in1施設', 'other', 'vimeo', 'vimeo', '76979871', 'Gubboru Facility Tour', '3-in-1 gym shop cafe', 'Gubboru设施介绍', '攀岩馆商店咖啡馆3合1', 'Gubboru 시설소개', '짐샵카페 3in1'),
('https://vimeo.com/148751763', 'V15プロジェクト記録', '最高難易度への挑戦ドキュメント', 'bouldering', 'vimeo', 'vimeo', '148751763', 'V15 Project Documentary', 'Challenge to highest difficulty', 'V15项目记录', '挑战最高难度纪录', 'V15 프로젝트', '최고난이도 도전');

-- Instagram Reels (using embed-compatible format)
INSERT INTO videos (url, title, description, category, platform, media_source, video_id_external, title_en, description_en, title_zh, description_zh, title_ko, description_ko) VALUES
('https://www.instagram.com/reel/C5vN8JKyXYZ', 'ナポリ式エスプレッソ×クライミング', 'カフェ併設ジムの魅力', 'other', 'instagram', 'instagram', 'C5vN8JKyXYZ', 'Napoli Espresso × Climbing', 'Cafe-attached gym appeal', '那不勒斯咖啡×攀岩', '咖啡馆附设攀岩馆魅力', '나폴리 에스프레소×클라이밍', '카페병설짐의 매력'),
('https://www.instagram.com/reel/C4ABC123xyz', '最新V14セッション', 'トップクライマーの挑戦', 'bouldering', 'instagram', 'instagram', 'C4ABC123xyz', 'Latest V14 Session', 'Top climbers challenge', '最新V14环节', '顶级攀岩者挑战', '최신 V14 세션', '톱클라이머 도전');

-- TikTok Videos
INSERT INTO videos (url, title, description, category, platform, media_source, video_id_external, title_en, description_en, title_zh, description_zh, title_ko, description_ko) VALUES
('https://www.tiktok.com/@climbing/video/7234567890123456789', 'V0からV5への成長記録', '初心者1ヶ月の上達', 'tutorial', 'tiktok', 'tiktok', '7234567890123456789', 'V0 to V5 Progress', 'Beginner 1-month improvement', 'V0到V5进步记录', '初学者1个月进步', 'V0→V5 성장기록', '초보자 1개월 성장');

-- 5 Climbing/Bouldering Blog Posts
INSERT INTO blog_posts (title, content, image_url, published_date, title_en, content_en, title_zh, content_zh, title_ko, content_ko) VALUES
('マルチピッチクライミング完全ガイド', '<h2>マルチピッチとは？</h2><p>複数のピッチを連続して登るクライミング技術です。30年の経験から、安全なビレイ技術とロープワークを解説します。</p><h2>必要な装備</h2><p>ハーネス、ロープ、カラビナ、確保器など。グッぼるショップで全て揃います。</p><h2>岩場での実践</h2><p>彦根周辺の岩場で実践できます。年間2.5万人が利用するジムで基礎を学びましょう。</p>', '/images/blog/multipitch.jpg', '2024-11-20', 'Complete Multipitch Climbing Guide', '<h2>What is Multipitch?</h2><p>Climbing technique connecting multiple pitches. 30 years experience teaching safe belay and ropework.</p><h2>Required Gear</h2><p>Harness, rope, carabiners, belay device - all available at Gubboru Shop.</p><h2>Practice at Crag</h2><p>Practice at crags around Hikone. Learn basics at gym with 25,000 annual users.</p>', '多段攀岩完全指南', '<h2>什么是多段攀岩？</h2><p>连续攀爬多个段落的技术。30年经验教授安全保护和绳索技术。</p><h2>必要装备</h2><p>安全带、绳索、快挂、保护器等-Gubboru商店全齐。</p><h2>岩场实践</h2><p>在彦根周边岩场实践。在年接待2.5万人的攀岩馆学习基础。</p>', '멀티피치 클라이밍 완전가이드', '<h2>멀티피치란?</h2><p>여러 피치를 연속으로 오르는 기술. 30년 경험으로 안전한 빌레이와 로프워크 해설.</p><h2>필요 장비</h2><p>하네스, 로프, 카라비너, 확보기 등-Gubboru샵에서 구비.</p><h2>암장 실천</h2><p>히코네 주변 암장에서 실천. 연 2.5만명 이용 짐에서 기초 학습.</p>'),

('ボルダリングV難度攻略法', '<h2>V0からV10までの道のり</h2><p>グッぼるボルダリングの課題管理システムで、あなたの登攀データを分析。効率的な上達法を30年の経験から伝授します。</p><h2>肩甲骨主導のムーブ</h2><p>小円筋と肩甲骨を意識したフォームが重要。筋力ではなく体幹で登ります。</p><h2>120モデルのシューズ選び</h2><p>グレードに合わせた最適なシューズ選びも重要。試履き→ジム試登で確認できます。</p>', '/images/blog/v-grades.jpg', '2024-11-18', 'Bouldering V-Grade Strategy', '<h2>Journey from V0 to V10</h2><p>Analyze your climbing data with Gubboru problem management system. Learn efficient progression from 30 years experience.</p><h2>Scapula-Driven Movement</h2><p>Focus on teres minor and scapula form. Climb with core, not muscle strength.</p><h2>Choosing from 120 Shoe Models</h2><p>Optimal shoe selection matters. Try-on → gym test available.</p>', '抱石V难度攻略', '<h2>V0到V10之路</h2><p>用Gubboru线路管理系统分析攀爬数据。30年经验传授高效进步法。</p><h2>肩胛骨主导动作</h2><p>注意小圆肌和肩胛骨姿势。用核心不用肌肉力量攀爬。</p><h2>120款鞋子选择</h2><p>根据难度选最佳鞋子。可试穿→攀岩馆测试。</p>', '볼더링 V난이도 공략법', '<h2>V0부터 V10까지</h2><p>Gubboru 과제관리시스템으로 등반데이터 분석. 30년 경험의 효율적 성장법.</p><h2>견갑골 주도 무브</h2><p>소원근과 견갑골 의식한 폼 중요. 근력이 아닌 코어로 등반.</p><h2>120모델 슈즈선택</h2><p>난이도별 최적 슈즈선택 중요. 시착→짐테스트 가능.</p>'),

('クライミングと環境保全活動', '<h2>プロギングとは</h2><p>ジョギングしながらゴミ拾い。プロギングジャパン副会長として年間30回超のイベントを開催。延べ4,000人参加で2.4トン回収。</p><h2>スターバックスとの協業</h2><p>企業と連携した地域活性化。クライミングコミュニティの環境意識向上を目指します。</p><h2>SDGsへの取り組み</h2><p>彦根駅前の遊休物件再生プロジェクト。クライミング施設を核とした地域創生。</p>', '/images/blog/plogging.jpg', '2024-11-15', 'Climbing and Environmental Conservation', '<h2>What is Plogging</h2><p>Picking trash while jogging. As Plogging Japan VP, host 30+ events yearly. 4,000 participants collected 2.4 tons.</p><h2>Starbucks Collaboration</h2><p>Regional revitalization with corporate partners. Raising environmental awareness in climbing community.</p><h2>SDGs Initiative</h2><p>Hikone Station vacant property regeneration. Regional revitalization centered on climbing facility.</p>', '攀岩与环保活动', '<h2>什么是拾荒慢跑</h2><p>边慢跑边捡垃圾。作为拾荒慢跑日本副会长，每年举办30+活动。4,000人参与回收2.4吨。</p><h2>星巴克合作</h2><p>与企业合作地区振兴。提高攀岩社区环保意识。</p><h2>SDGs措施</h2><p>彦根站前闲置物业再生。以攀岩设施为核心的地区创生。</p>', '클라이밍과 환경보전', '<h2>플로깅이란</h2><p>조깅하며 쓰레기줍기. 플로깅재팬 부회장으로 연30회+ 이벤트. 4,000명 참가 2.4톤 회수.</p><h2>스타벅스 협업</h2><p>기업과 지역활성화. 클라이밍커뮤니티 환경의식 향상.</p><h2>SDGs 대응</h2><p>히코네역 유휴물건 재생. 클라이밍시설 중심 지역창생.</p>'),

('クライミングジム選びのポイント', '<h2>ジム・ショップ・カフェ一体型の魅力</h2><p>グッぼるは日本唯一の3in1施設。年間2.5万人が利用する課題管理システムで、あなたの成長を可視化します。</p><h2>120モデルのシューズ在庫</h2><p>LINE接客→EC→試履き→ジム試登の一気通貫サービス。クラッシュパッド60枚超の圧倒的在庫。</p><h2>ナポリ式エスプレッソ</h2><p>カフェ併設でクライミング前後のリラックス。IoT計測で豆の鮮度管理。</p>', '/images/blog/gym-selection.jpg', '2024-11-12', 'Choosing the Right Climbing Gym', '<h2>Gym-Shop-Cafe Integration</h2><p>Gubboru is Japan only 3-in-1 facility. Problem management system used by 25,000 annually visualizes your growth.</p><h2>120 Shoe Models Stock</h2><p>LINE service → EC → try-on → gym test integration. 60+ crash pads overwhelming inventory.</p><h2>Napoli Espresso</h2><p>Cafe for pre/post climbing relaxation. IoT bean freshness monitoring.</p>', '攀岩馆选择要点', '<h2>攀岩馆商店咖啡馆一体魅力</h2><p>Gubboru是日本唯一3合1设施。年2.5万人使用的线路管理系统可视化您的成长。</p><h2>120款鞋子库存</h2><p>LINE接待→电商→试穿→攀岩馆测试一站式。60+抱石垫压倒性库存。</p><h2>那不勒斯咖啡</h2><p>咖啡馆供攀岩前后放松。物联网监测豆子新鲜度。</p>', '클라이밍짐 선택 포인트', '<h2>짐샵카페 일체형 매력</h2><p>Gubboru는 일본유일 3in1시설. 연2.5만명 이용 과제관리시스템으로 성장 가시화.</p><h2>120모델 슈즈재고</h2><p>LINE접객→EC→시착→짐테스트 통합서비스. 60+크래시패드 압도적재고.</p><h2>나폴리 에스프레소</h2><p>카페에서 클라이밍 전후 휴식. IoT 원두신선도 관리.</p>'),

('クライミング施設開業コンサルティング', '<h2>14施設の立ち上げ実績</h2><p>事業再構築補助金採択率85%。アウトドア×ウェルビーイング産業への投資実績1.8億円。</p><h2>データドリブン経営</h2><p>課題管理システム、IoTセンサー、MES連携でコスト75%削減。年間2.5万人のデータ活用ノウハウ。</p><h2>複合事業モデル</h2><p>ジム×ショップ×カフェ、Notエステとの連携、rasiku看護師AIチャットなど、クライミングを核とした多角展開。</p>', '/images/blog/consulting.jpg', '2024-11-10', 'Climbing Facility Opening Consultation', '<h2>14 Facility Launch Results</h2><p>85% subsidy approval rate. 180M yen investment in outdoor × wellbeing industry.</p><h2>Data-Driven Management</h2><p>Problem management system, IoT sensors, MES integration - 75% cost reduction. Utilizing data from 25,000 annual users.</p><h2>Multi-Business Model</h2><p>Gym×Shop×Cafe, Not Esthe collaboration, rasiku nurse AI chat - diversified development centered on climbing.</p>', '攀岩设施开业咨询', '<h2>14设施启动实绩</h2><p>补贴批准率85%。户外×健康产业投资1.8亿日元。</p><h2>数据驱动经营</h2><p>线路管理系统、物联网传感器、MES联动-成本削减75%。活用年2.5万人数据诀窍。</p><h2>复合事业模式</h2><p>攀岩馆×商店×咖啡馆，Not美容合作，rasiku护士AI聊天等-以攀岩为核心多角发展。</p>', '클라이밍시설 개업컨설팅', '<h2>14시설 런칭실적</h2><p>보조금채택률85%. 아웃도어×웰빙산업 투자1.8억엔.</p><h2>데이터드리븐 경영</h2><p>과제관리시스템, IoT센서, MES연계로 비용75%절감. 연2.5만명 데이터활용 노하우.</p><h2>복합사업모델</h2><p>짐×샵×카페, Not에스테 연계, rasiku간호사AI채팅 등-클라이밍 중심 다각전개.</p>');

-- 2 Announcements (only 2 will be shown by default)
INSERT INTO announcements (title, content, priority, is_active, title_en, content_en, title_zh, content_zh, title_ko, content_ko) VALUES
('🎉 V16新課題リリース', '30年のクライミング経験を活かした最高難易度課題が登場！肩甲骨と小円筋を駆使する革新的ムーブを体験してください。', 1, 1, '🎉 New V16 Problem Released', '30 years experience created highest difficulty problem! Experience innovative movement using scapula and teres minor.', '🎉 V16新线路发布', '30年攀岩经验创造最高难度线路！体验使用肩胛骨和小圆肌的创新动作。', '🎉 V16 신규과제', '30년 경험으로 만든 최고난이도! 견갑골과 소원근 활용 혁신무브 체험.'),

('☕ カフェ新メニュー×プロギングイベント', 'ナポリ直送豆の新エスプレッソメニュー登場！次回プロギングは12/15(日)、スターバックスとのコラボイベントです。', 1, 1, '☕ New Cafe Menu × Plogging Event', 'New espresso with Naples beans! Next plogging 12/15(Sun), Starbucks collaboration event.', '☕ 咖啡馆新菜单×拾荒活动', '那不勒斯豆子新咖啡！下次拾荒12/15(周日)，星巴克合作活动。', '☕ 카페신메뉴×플로깅', '나폴리원두 신메뉴! 다음 플로깅12/15(일), 스타벅스 콜라보.');
